// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEP490.DB;

#nullable disable

namespace SEP490.DB.Migrations
{
    [DbContext(typeof(SEP490DbContext))]
    [Migration("20250621053525_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SEP490.DB.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_person");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext")
                        .HasColumnName("customer_name");

                    b.Property<decimal?>("Debt")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("debt");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("discount");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_supplier");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("TaxCode")
                        .HasColumnType("longtext")
                        .HasColumnName("tax_code");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext")
                        .HasColumnName("customer_name");

                    b.Property<string>("OrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("QuantityDelivered")
                        .HasColumnType("int")
                        .HasColumnName("quantity_delivered");

                    b.Property<int>("QuantityToDeliver")
                        .HasColumnType("int")
                        .HasColumnName("quantity_to_deliver");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_value");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_deliveries_purchase_order_id");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.DeliveryDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("height");

                    b.Property<string>("ProductCode")
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Thickness")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("thickness");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_delivery_details");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_delivery_details_delivery_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_delivery_details_product_id");

                    b.ToTable("delivery_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.GlassStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AdhesiveLayers")
                        .HasColumnType("int")
                        .HasColumnName("adhesive_layers");

                    b.Property<decimal>("AdhesiveThickness")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("adhesive_thickness");

                    b.Property<string>("AdhesiveType")
                        .HasColumnType("longtext")
                        .HasColumnName("adhesive_type");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Composition")
                        .HasColumnType("longtext")
                        .HasColumnName("composition");

                    b.Property<string>("EdgeType")
                        .HasColumnType("longtext")
                        .HasColumnName("edge_type");

                    b.Property<int>("GlassLayers")
                        .HasColumnType("int")
                        .HasColumnName("glass_layers");

                    b.Property<string>("ProductCode")
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.HasKey("Id")
                        .HasName("pk_glass_structures");

                    b.ToTable("glass_structures", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CostObject")
                        .HasColumnType("longtext")
                        .HasColumnName("cost_object");

                    b.Property<string>("DocumentCode")
                        .HasColumnType("longtext")
                        .HasColumnName("document_code");

                    b.Property<string>("ProductCode")
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductionOrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("production_order_code");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.Property<string>("Warehouse")
                        .HasColumnType("longtext")
                        .HasColumnName("warehouse");

                    b.Property<int?>("WarehouseIssueId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_issue_id");

                    b.Property<int?>("WarehouseReceiptId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_receipt_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_transactions_product_id");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_inventory_transactions_production_order_id");

                    b.HasIndex("WarehouseIssueId")
                        .HasDatabaseName("ix_inventory_transactions_warehouse_issue_id");

                    b.HasIndex("WarehouseReceiptId")
                        .HasDatabaseName("ix_inventory_transactions_warehouse_receipt_id");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("OrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("order_code");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_details");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_order_details_purchase_order_id");

                    b.ToTable("order_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetailProduct", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("OrderDetailId", "ProductId")
                        .HasName("pk_order_detail_products");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_detail_products_product_id");

                    b.ToTable("order_detail_products", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("GlassCode")
                        .HasColumnType("longtext")
                        .HasColumnName("glass_code");

                    b.Property<int>("GlassStructureId")
                        .HasColumnType("int")
                        .HasColumnName("glass_structure_id");

                    b.Property<string>("Length")
                        .HasColumnType("longtext")
                        .HasColumnName("length");

                    b.Property<string>("ProductCode")
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductType")
                        .HasColumnType("longtext")
                        .HasColumnName("product_type");

                    b.Property<decimal?>("Thickness")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("thickness");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("weight");

                    b.Property<string>("Width")
                        .HasColumnType("longtext")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("GlassStructureId")
                        .HasDatabaseName("ix_products_glass_structure_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("IssueCode")
                        .HasColumnType("longtext")
                        .HasColumnName("issue_code");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("ProductionOrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("production_order_code");

                    b.Property<string>("ProductionPlanCode")
                        .HasColumnType("longtext")
                        .HasColumnName("production_plan_code");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("int")
                        .HasColumnName("production_plan_id");

                    b.Property<string>("ReceiptCode")
                        .HasColumnType("longtext")
                        .HasColumnName("receipt_code");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_production_orders");

                    b.HasIndex("ProductionPlanId")
                        .HasDatabaseName("ix_production_orders_production_plan_id");

                    b.ToTable("production_orders", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("OrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("order_code");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("plan_date");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_production_plans");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_production_plans_customer_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_production_plans_purchase_order_id");

                    b.ToTable("production_plans", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("delivery_status");

                    b.Property<string>("OrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("order_code");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<decimal?>("OrderValue")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("order_value");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_purchase_orders_customer_id");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.TestTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_table");

                    b.ToTable("test_table", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.WarehouseIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("accounting_date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("DocumentCode")
                        .HasColumnType("longtext")
                        .HasColumnName("document_code");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("document_date");

                    b.Property<string>("IssueReason")
                        .HasColumnType("longtext")
                        .HasColumnName("issue_reason");

                    b.Property<string>("ProductionOrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("production_order_code");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<string>("Receiver")
                        .HasColumnType("longtext")
                        .HasColumnName("receiver");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_issues");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_warehouse_issues_production_order_id");

                    b.ToTable("warehouse_issues", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.WarehouseReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("accounting_date");

                    b.Property<string>("Deliverer")
                        .HasColumnType("longtext")
                        .HasColumnName("deliverer");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("DocumentCode")
                        .HasColumnType("longtext")
                        .HasColumnName("document_code");

                    b.Property<string>("ProductionOrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("production_order_code");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_receipts");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_warehouse_receipts_production_order_id");

                    b.ToTable("warehouse_receipts", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Delivery", b =>
                {
                    b.HasOne("SEP490.DB.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_purchase_orders_purchase_order_id");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.DeliveryDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_details_deliveries_delivery_id");

                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_details_products_product_id");

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SEP490.DB.Models.InventoryTransaction", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_inventory_transactions_production_orders_production_order_id");

                    b.HasOne("SEP490.DB.Models.WarehouseIssue", "WarehouseIssue")
                        .WithMany()
                        .HasForeignKey("WarehouseIssueId")
                        .HasConstraintName("fk_inventory_transactions_warehouse_issues_warehouse_issue_id");

                    b.HasOne("SEP490.DB.Models.WarehouseReceipt", "WarehouseReceipt")
                        .WithMany()
                        .HasForeignKey("WarehouseReceiptId")
                        .HasConstraintName("fk_inventory_transactions_warehouse_receipts_warehouse_receipt_");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");

                    b.Navigation("WarehouseIssue");

                    b.Navigation("WarehouseReceipt");
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_details_purchase_orders_purchase_order_id");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetailProduct", b =>
                {
                    b.HasOne("SEP490.DB.Models.OrderDetail", "OrderDetail")
                        .WithMany()
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_detail_products_order_details_order_detail_id");

                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_detail_products_products_product_id");

                    b.Navigation("OrderDetail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SEP490.DB.Models.Product", b =>
                {
                    b.HasOne("SEP490.DB.Models.GlassStructure", "GlassStructure")
                        .WithMany()
                        .HasForeignKey("GlassStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_glass_structures_glass_structure_id");

                    b.Navigation("GlassStructure");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOrder", b =>
                {
                    b.HasOne("SEP490.DB.Models.ProductionPlan", "ProductionPlan")
                        .WithMany()
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_orders_production_plans_production_plan_id");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionPlan", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_plans_customers_customer_id");

                    b.HasOne("SEP490.DB.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_plans_purchase_orders_purchase_order_id");

                    b.Navigation("Customer");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.PurchaseOrder", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SEP490.DB.Models.WarehouseIssue", b =>
                {
                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_warehouse_issues_production_orders_production_order_id");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.WarehouseReceipt", b =>
                {
                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_warehouse_receipts_production_orders_production_order_id");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.Customer", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
