// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEP490.DB;

#nullable disable

namespace SEP490.DB.Migrations
{
    [DbContext(typeof(SEP490DbContext))]
    [Migration("20250723032504_UpdateDatabaseNew2-Kiet")]
    partial class UpdateDatabaseNew2Kiet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SEP490.DB.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_accounts_employee_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_accounts_role_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ChemicalExportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("quantity");

                    b.Property<string>("UOM")
                        .HasColumnType("longtext")
                        .HasColumnName("uom");

                    b.HasKey("Id")
                        .HasName("pk_chemical_export_details");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_chemical_export_details_product_id");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_chemical_export_details_production_order_id");

                    b.ToTable("chemical_export_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_person");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("longtext")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext")
                        .HasColumnName("customer_name");

                    b.Property<decimal?>("Debt")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("debt");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("discount");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_supplier");

                    b.Property<int>("PartnerType")
                        .HasColumnType("int")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("TaxCode")
                        .HasColumnType("longtext")
                        .HasColumnName("tax_code");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.CutGlassInvoiceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int>("productId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("productionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_cut_glass_invoice_materials");

                    b.HasIndex("productId")
                        .HasDatabaseName("ix_cut_glass_invoice_materials_product_id");

                    b.HasIndex("productionOrderId")
                        .HasDatabaseName("ix_cut_glass_invoice_materials_production_order_id");

                    b.ToTable("cut_glass_invoice_materials", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.CutGlassInvoiceOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CutGlassInvoiceMaterialId")
                        .HasColumnType("int")
                        .HasColumnName("cut_glass_invoice_material_id");

                    b.Property<bool>("IsDC")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_dc");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int>("ProductionOutputId")
                        .HasColumnType("int")
                        .HasColumnName("production_output_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cut_glass_invoice_outputs");

                    b.HasIndex("CutGlassInvoiceMaterialId")
                        .HasDatabaseName("ix_cut_glass_invoice_outputs_cut_glass_invoice_material_id");

                    b.HasIndex("ProductionOutputId")
                        .HasDatabaseName("ix_cut_glass_invoice_outputs_production_output_id");

                    b.ToTable("cut_glass_invoice_outputs", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Debts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("int")
                        .HasColumnName("invoice_type");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("paid_amount");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("remaining_amount");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_debts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_debts_customer_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_debts_invoice_id");

                    b.ToTable("debts", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int")
                        .HasColumnName("sales_order_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("SalesOrderId")
                        .HasDatabaseName("ix_deliveries_sales_order_id");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.DeliveryDetail", b =>
                {
                    b.Property<int>("DeliveryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("delivery_detail_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("DeliveryDetailId")
                        .HasName("pk_delivery_details");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_delivery_details_delivery_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_delivery_details_product_id");

                    b.ToTable("delivery_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.DeliveryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int>("ProductionPlanDetailId")
                        .HasColumnType("int")
                        .HasColumnName("production_plan_detail_id");

                    b.Property<int>("QuantityDelivered")
                        .HasColumnType("int")
                        .HasColumnName("quantity_delivered");

                    b.HasKey("Id")
                        .HasName("pk_delivery_histories");

                    b.HasIndex("ProductionPlanDetailId")
                        .HasDatabaseName("ix_delivery_histories_production_plan_detail_id");

                    b.ToTable("delivery_histories", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("longtext")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.FinishedGoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<string>("QualityLevel")
                        .HasColumnType("longtext")
                        .HasColumnName("quality_level");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_finished_goods");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_finished_goods_product_id");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_finished_goods_production_order_id");

                    b.ToTable("finished_goods", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Formular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<double>("Ratio")
                        .HasColumnType("double")
                        .HasColumnName("ratio");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_formulars");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_formulars_product_id");

                    b.ToTable("formulars", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.GlassStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AdhesiveLayers")
                        .HasColumnType("int")
                        .HasColumnName("adhesive_layers");

                    b.Property<decimal?>("AdhesiveThickness")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("adhesive_thickness");

                    b.Property<string>("AdhesiveType")
                        .HasColumnType("longtext")
                        .HasColumnName("adhesive_type");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Composition")
                        .HasColumnType("longtext")
                        .HasColumnName("composition");

                    b.Property<string>("EdgeType")
                        .HasColumnType("longtext")
                        .HasColumnName("edge_type");

                    b.Property<int?>("GlassLayers")
                        .HasColumnType("int")
                        .HasColumnName("glass_layers");

                    b.Property<string>("ProductCode")
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<int?>("UnitPrice")
                        .HasColumnType("int")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_glass_structures");

                    b.ToTable("glass_structures", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.GlueButylExportInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<string>("Products")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("products");

                    b.HasKey("Id")
                        .HasName("pk_glue_butyl_export_invoices");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_glue_butyl_export_invoices_employee_id");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_glue_butyl_export_invoices_production_order_id");

                    b.ToTable("glue_butyl_export_invoices", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("invoice_date");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("int")
                        .HasColumnName("invoice_type");

                    b.Property<int?>("RelatedOrderId")
                        .HasColumnType("int")
                        .HasColumnName("related_order_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tax");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_invoices_customer_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.InvoiceDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoice_details");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_details_invoice_id");

                    b.ToTable("invoice_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int")
                        .HasColumnName("chunk_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("OrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("order_code");

                    b.Property<int>("SaleOrderId")
                        .HasColumnType("int")
                        .HasColumnName("sale_order_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_order_details");

                    b.HasIndex("SaleOrderId")
                        .HasDatabaseName("ix_order_details_sale_order_id");

                    b.ToTable("order_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetailProduct", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.HasKey("OrderDetailId", "ProductId")
                        .HasName("pk_order_detail_products");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_detail_products_product_id");

                    b.ToTable("order_detail_products", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("int")
                        .HasColumnName("invoice_type");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payments_customer_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("GlassStructureId")
                        .HasColumnType("int")
                        .HasColumnName("glass_structure_id");

                    b.Property<string>("Height")
                        .HasColumnType("longtext")
                        .HasColumnName("height");

                    b.Property<string>("ProductCode")
                        .HasColumnType("longtext")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductType")
                        .HasColumnType("longtext")
                        .HasColumnName("product_type");

                    b.Property<decimal?>("Thickness")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("thickness");

                    b.Property<string>("UOM")
                        .HasColumnType("longtext")
                        .HasColumnName("uom");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("weight");

                    b.Property<string>("Width")
                        .HasColumnType("longtext")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("GlassStructureId")
                        .HasDatabaseName("ix_products_glass_structure_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionDefects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DefectStage")
                        .HasColumnType("longtext")
                        .HasColumnName("defect_stage");

                    b.Property<string>("DefectType")
                        .HasColumnType("longtext")
                        .HasColumnName("defect_type");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reported_at");

                    b.HasKey("Id")
                        .HasName("pk_production_defects");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_defects_product_id");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_production_defects_production_order_id");

                    b.ToTable("production_defects", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductionOutputId")
                        .HasColumnType("int")
                        .HasColumnName("production_output_id");

                    b.Property<int?>("UOM")
                        .HasColumnType("int")
                        .HasColumnName("uom");

                    b.HasKey("Id")
                        .HasName("pk_production_materials");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_materials_product_id");

                    b.HasIndex("ProductionOutputId")
                        .HasDatabaseName("ix_production_materials_production_output_id");

                    b.ToTable("production_materials", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("ProductionOrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("production_order_code");

                    b.Property<string>("ProductionPlanCode")
                        .HasColumnType("longtext")
                        .HasColumnName("production_plan_code");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("int")
                        .HasColumnName("production_plan_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<bool>("StatusDaNhapMisa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status_da_nhap_misa");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_production_orders");

                    b.HasIndex("ProductionPlanId")
                        .HasDatabaseName("ix_production_orders_production_plan_id");

                    b.ToTable("production_orders", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("productionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.HasKey("Id")
                        .HasName("pk_production_order_details");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_order_details_product_id");

                    b.HasIndex("productionOrderId")
                        .HasDatabaseName("ix_production_order_details_production_order_id");

                    b.ToTable("production_order_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<int?>("Defected")
                        .HasColumnType("int")
                        .HasColumnName("defected");

                    b.Property<int?>("Finished")
                        .HasColumnType("int")
                        .HasColumnName("finished");

                    b.Property<int?>("OutputFor")
                        .HasColumnType("int")
                        .HasColumnName("output_for");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("production_order_id");

                    b.Property<int?>("UOM")
                        .HasColumnType("int")
                        .HasColumnName("uom");

                    b.HasKey("Id")
                        .HasName("pk_production_outputs");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_outputs_product_id");

                    b.HasIndex("ProductionOrderId")
                        .HasDatabaseName("ix_production_outputs_production_order_id");

                    b.ToTable("production_outputs", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("plan_date");

                    b.Property<int?>("SaleOrderId")
                        .HasColumnType("int")
                        .HasColumnName("sale_order_id");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_production_plans");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_production_plans_customer_id");

                    b.HasIndex("SaleOrderId")
                        .HasDatabaseName("ix_production_plans_sale_order_id");

                    b.ToTable("production_plans", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionPlanDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("DaGiao")
                        .HasColumnType("int")
                        .HasColumnName("da_giao");

                    b.Property<decimal?>("DoDaiButyl")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("do_dai_butyl");

                    b.Property<int?>("Doday")
                        .HasColumnType("int")
                        .HasColumnName("doday");

                    b.Property<int>("Done")
                        .HasColumnType("int")
                        .HasColumnName("done");

                    b.Property<int?>("IsKinhCuongLuc")
                        .HasColumnType("int")
                        .HasColumnName("is_kinh_cuong_luc");

                    b.Property<int?>("Kinh4")
                        .HasColumnType("int")
                        .HasColumnName("kinh4");

                    b.Property<int?>("Kinh5")
                        .HasColumnType("int")
                        .HasColumnName("kinh5");

                    b.Property<int?>("LoaiButyl")
                        .HasColumnType("int")
                        .HasColumnName("loai_butyl");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("int")
                        .HasColumnName("production_plan_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("SoLopKeo")
                        .HasColumnType("int")
                        .HasColumnName("so_lop_keo");

                    b.Property<int?>("SoLopKinh")
                        .HasColumnType("int")
                        .HasColumnName("so_lop_kinh");

                    b.Property<decimal?>("TongKeoMem")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tong_keo_mem");

                    b.Property<decimal?>("TongKeoNano")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tong_keo_nano");

                    b.Property<int?>("UOM")
                        .HasColumnType("int")
                        .HasColumnName("uom");

                    b.HasKey("Id")
                        .HasName("pk_production_plan_details");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_plan_details_product_id");

                    b.HasIndex("ProductionPlanId")
                        .HasDatabaseName("ix_production_plan_details_production_plan_id");

                    b.ToTable("production_plan_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_value");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_purchase_orders_customer_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_purchase_orders_employee_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_order_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_price");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_details");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_order_details_product_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_details_purchase_order_id");

                    b.ToTable("purchase_order_details", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.SaleOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int")
                        .HasColumnName("delivery_status");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<string>("OrderCode")
                        .HasColumnType("longtext")
                        .HasColumnName("order_code");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<decimal?>("OrderValue")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("order_value");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sale_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sale_orders_customer_id");

                    b.ToTable("sale_orders", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.TestTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_table");

                    b.ToTable("test_table", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.ZaloToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("access_token_expires_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("refresh_token_expires_at");

                    b.HasKey("Id")
                        .HasName("pk_zalo_tokens");

                    b.ToTable("zalo_tokens", (string)null);
                });

            modelBuilder.Entity("SEP490.DB.Models.Account", b =>
                {
                    b.HasOne("SEP490.DB.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_employees_employee_id");

                    b.HasOne("SEP490.DB.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_roles_role_id");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SEP490.DB.Models.ChemicalExportDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_chemical_export_details_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_chemical_export_details_production_orders_production_order_id");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.CutGlassInvoiceMaterial", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cut_glass_invoice_materials_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("productionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cut_glass_invoice_materials_production_orders_production_ord");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.CutGlassInvoiceOutput", b =>
                {
                    b.HasOne("SEP490.DB.Models.CutGlassInvoiceMaterial", "CutGlassInvoiceMaterial")
                        .WithMany()
                        .HasForeignKey("CutGlassInvoiceMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cut_glass_invoice_outputs_cut_glass_invoice_materials_cut_gl");

                    b.HasOne("SEP490.DB.Models.ProductionOutput", "ProductionOutput")
                        .WithMany()
                        .HasForeignKey("ProductionOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cut_glass_invoice_outputs_production_outputs_production_outp");

                    b.Navigation("CutGlassInvoiceMaterial");

                    b.Navigation("ProductionOutput");
                });

            modelBuilder.Entity("SEP490.DB.Models.Debts", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_debts_customers_customer_id");

                    b.HasOne("SEP490.DB.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("fk_debts_invoices_invoice_id");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SEP490.DB.Models.Delivery", b =>
                {
                    b.HasOne("SEP490.DB.Models.SaleOrder", "SalesOrder")
                        .WithMany()
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_sale_orders_sales_order_id");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.DeliveryDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_details_deliveries_delivery_id");

                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_details_products_product_id");

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SEP490.DB.Models.DeliveryHistory", b =>
                {
                    b.HasOne("SEP490.DB.Models.ProductionPlanDetail", "ProductionPlanDetail")
                        .WithMany()
                        .HasForeignKey("ProductionPlanDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_histories_production_plan_details_production_plan_d");

                    b.Navigation("ProductionPlanDetail");
                });

            modelBuilder.Entity("SEP490.DB.Models.FinishedGoods", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_finished_goods_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_finished_goods_production_orders_production_order_id");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.Formular", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_formulars_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SEP490.DB.Models.GlueButylExportInvoice", b =>
                {
                    b.HasOne("SEP490.DB.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_glue_butyl_export_invoices_employees_employee_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_glue_butyl_export_invoices_production_orders_production_orde");

                    b.Navigation("Employee");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.Invoice", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SEP490.DB.Models.InvoiceDetails", b =>
                {
                    b.HasOne("SEP490.DB.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_details_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.SaleOrder", "SaleOrder")
                        .WithMany("OrderDetails")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_details_sale_orders_sale_order_id");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetailProduct", b =>
                {
                    b.HasOne("SEP490.DB.Models.OrderDetail", "OrderDetail")
                        .WithMany("OrderDetailProducts")
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_detail_products_order_details_order_detail_id");

                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_detail_products_products_product_id");

                    b.Navigation("OrderDetail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SEP490.DB.Models.Payments", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_customers_customer_id");

                    b.HasOne("SEP490.DB.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SEP490.DB.Models.Product", b =>
                {
                    b.HasOne("SEP490.DB.Models.GlassStructure", "GlassStructure")
                        .WithMany()
                        .HasForeignKey("GlassStructureId")
                        .HasConstraintName("fk_products_glass_structures_glass_structure_id");

                    b.Navigation("GlassStructure");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionDefects", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_production_defects_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_production_defects_production_orders_production_order_id");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionMaterial", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_materials_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOutput", "ProductionOutput")
                        .WithMany()
                        .HasForeignKey("ProductionOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_materials_production_outputs_production_output_id");

                    b.Navigation("Product");

                    b.Navigation("ProductionOutput");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOrder", b =>
                {
                    b.HasOne("SEP490.DB.Models.ProductionPlan", "ProductionPlan")
                        .WithMany()
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_orders_production_plans_production_plan_id");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOrderDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_order_details_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("productionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_order_details_production_orders_production_order_");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionOutput", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_outputs_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .HasConstraintName("fk_production_outputs_production_orders_production_order_id");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionPlan", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_production_plans_customers_customer_id");

                    b.HasOne("SEP490.DB.Models.SaleOrder", "SaleOrder")
                        .WithMany()
                        .HasForeignKey("SaleOrderId")
                        .HasConstraintName("fk_production_plans_sale_orders_sale_order_id");

                    b.Navigation("Customer");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionPlanDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_plan_details_products_product_id");

                    b.HasOne("SEP490.DB.Models.ProductionPlan", "ProductionPlan")
                        .WithMany("ProductionPlanDetails")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_plan_details_production_plans_production_plan_id");

                    b.Navigation("Product");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("SEP490.DB.Models.PurchaseOrder", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_purchase_orders_customers_customer_id");

                    b.HasOne("SEP490.DB.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_purchase_orders_employees_employee_id");

                    b.HasOne("SEP490.DB.Models.Customer", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_purchase_orders_customers_supplier_id");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SEP490.DB.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("SEP490.DB.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_purchase_order_details_products_product_id");

                    b.HasOne("SEP490.DB.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_details_purchase_orders_purchase_order_id");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SEP490.DB.Models.SaleOrder", b =>
                {
                    b.HasOne("SEP490.DB.Models.Customer", "Customer")
                        .WithMany("SaleOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_orders_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SEP490.DB.Models.Customer", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("SaleOrders");
                });

            modelBuilder.Entity("SEP490.DB.Models.OrderDetail", b =>
                {
                    b.Navigation("OrderDetailProducts");
                });

            modelBuilder.Entity("SEP490.DB.Models.ProductionPlan", b =>
                {
                    b.Navigation("ProductionPlanDetails");
                });

            modelBuilder.Entity("SEP490.DB.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("SEP490.DB.Models.SaleOrder", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
